### ISSUE TITLE
Jmeter authentication project compatible with last Jmeter versions

### ISSUE THREAD

**Issue by oscarlopezsastre** [NogaCohen/Social-Network-Authentication-Load-Testing-with-JMeter#1]
Hi Noga Cohen,

Thanks for your support.
I am having an issue when I try to open the jmx file with some of the last Jmeter releases. The jmx file could not be opened with this log info:
```
2021-09-09 09:42:32,793 ERROR o.a.j.u.JMeterUtils: Problem loading XML from:'\apache-jmeter-5.4.1\scripts\Social Network Authorization.jmx'. 
Cause:
CannotResolveClassException: html
 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: html
```
 
 I don't know if the root cause is my Jmeter release or the JVM installed, but I have not been able to open your jmx project.
 Could you please update the project so that it can work with the last Jmeter release?

Thanks and best regards

This is the full log:
```
2021-09-09 09:42:32,757 INFO o.a.j.s.SaveService: Loading file: \apache-jmeter-5.4.1\scripts\Social Network Authorization.jmx
2021-09-09 09:42:32,768 WARN o.j.r.p.TestPlanAnalyzer: Cannot parse file: \apache-jmeter-5.4.1\scripts\Social Network Authorization.jmx
org.xml.sax.SAXParseException: Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source) ~[?:1.8.0_211]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.getNodeListWithClassNames(TestPlanAnalyzer.java:106) ~[jmeter-plugins-manager-1.6.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.analyze(TestPlanAnalyzer.java:36) ~[jmeter-plugins-manager-1.6.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.analyzeTestPlan(PluginSuggester.java:51) ~[jmeter-plugins-manager-1.6.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.findPluginsToInstall(PluginSuggester.java:44) ~[jmeter-plugins-manager-1.6.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.checkAndSuggest(PluginSuggester.java:28) ~[jmeter-plugins-manager-1.6.jar:?]
	at org.jmeterplugins.repository.logging.LoggerAppender.append(LoggerAppender.java:33) ~[jmeter-plugins-manager-1.6.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:543) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:485) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:460) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161) ~[log4j-core-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2198) ~[log4j-api-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2152) ~[log4j-api-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2135) ~[log4j-api-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028) ~[log4j-api-2.13.3.jar:2.13.3]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899) ~[log4j-api-2.13.3.jar:2.13.3]
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184) ~[log4j-slf4j-impl-2.13.3.jar:2.13.3]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:428) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.Load.doActionAfterCheck(Load.java:88) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.4.1]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_211]
2021-09-09 09:42:32,792 WARN o.a.j.g.a.Load: Unexpected error. java.lang.IllegalArgumentException: Problem loading XML from:'C:\Users\olopez.sastre\Desktop\apache-jmeter-5.4.1\scripts\Social Network Authorization.jmx'. 
Cause:
CannotResolveClassException: html

 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: html
java.lang.IllegalArgumentException: Problem loading XML from:'\apache-jmeter-5.4.1\scripts\Social Network Authorization.jmx'. 
Cause:
CannotResolveClassException: html

 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: html
	at org.apache.jmeter.save.SaveService.readTree(SaveService.java:459) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:432) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.Load.doActionAfterCheck(Load.java:88) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.4.1]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_211]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_211]
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: html
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at org.apache.jmeter.save.SaveService$XStreamWrapper$1.realClass(SaveService.java:97) ~[ApacheJMeter_core.jar:5.4.1]
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1409) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1388) ~[xstream-1.4.15.jar:1.4.15]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1273) ~[xstream-1.4.15.jar:1.4.15]
	at org.apache.jmeter.save.SaveService.readTree(SaveService.java:449) ~[ApacheJMeter_core.jar:5.4.1]
	... 21 more
2021-09-09 09:42:32,793 ERROR o.a.j.u.JMeterUtils: Problem loading XML from:'\apache-jmeter-5.4.1\scripts\Social Network Authorization.jmx'. 
Cause:
CannotResolveClassException: html

 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: html

```

**Comment by oscarlopezsastre** [comment]
in the .gitignore directory there is a valid Jmeter script.

best regards
